global using System.ComponentModel.DataAnnotations;
global using Attendance_Time_tracking_System.Data;
global using Attendance_Time_tracking_System.ViewModels;
global using Attendance_Time_tracking_System.Models;
global using Microsoft.EntityFrameworkCore;